name: Jobs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PMD
        run: echo "hellooooooooooooo"
      - name: Build
        run: |
          echo "Build successfully"
  pmd:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PMD
        run: echo "hellooooooooooooo"
      - name: Run PMD
        uses: github/pmd-action@v1
        with:
          rulesets: java-basic,java-braces
          fail-on-violations: true

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "test passed"

