name:
  First Cron Job

on:
  push:
  schedule:
    - cron: "*/1 * * * *"
 
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run pipeline
        run: |
          if [[ $(git rev-list --count HEAD..HEAD@{1w}) -gt 0 ]]; then
            echo "There has been a commit this week, running pipeline..."
            pipenv install
            pipenv run test
          else
            echo "No commits this week, skipping pipeline..."
          fi
