name: Jobs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PMD
        run: echo "hellooooooooooooo"
      - name: Build
        run: |
          echo "Build successfully"
  pmd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PMD
        run: echo "hellooooooooooooo"
      - name: Run PMD2
        run: exit 1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "test passed"
          echo ${{ needs.pmd.result }}

