name: Parallel Matrix Jobs

on:
  push:
    branches:
      - '**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || matrix.java_version == 17 }}

    strategy:
      fail-fast: true
      matrix:
        java_version: [17, 11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}

      # Add your build and test steps here
      # For example:
      - name: Build and Test with Java ${{ matrix.java_version }}
        run: |
          mvn clean install
