name: Parallel Matrix Jobs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Build
        run: |
          echo "Build successfully"
  pmd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Run PMD
        uses: github/pmd-action@v1
        with:
          rulesets: java-basic,java-braces
          fail-on-violations: true

  test:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Test
        run: |
          echo "test passed"

